Added Option to filter in LoggedBlocks List (GUI)
CuukyOfficial/VaroPlugin pull request #66
Opened 2022-01-07 18:13 UTC by borekking

2022-01-08 19:19 UTC, Almighty-Satan requested changes

2022-01-08 19:19 UTC, Almighty-Satan commented on src/de/cuuky/varo/gui/admin/orelogger/OreLoggerFilterGUI.java
> +        addItem(24 + 9, new BuildItem().material(Material.REDSTONE).displayName(Main.getColorCode() + "Reset Material").build(),
```suggestion
        addItem(24 + 9, new BuildItem().material(Material.REDSTONE).displayName(ChatColor.RED + "Reset Material").build(),
```

2022-01-08 19:20 UTC, UeberallGebannt commented
Vorschlag: LanguageSystem benutzen statt Nachrichten zu hardcoden

2022-01-08 19:31 UTC, Almighty-Satan commented
The user should also get an error message when attempting to sort by an invalid player or material

2022-01-10 19:08 UTC, CuukyOfficial commented
Please use Materials.* instead of Material.* in every BuildItem#material call. Thanks. :)

2022-01-12 18:56 UTC, UeberallGebannt commented
Please use the replace() method instead of replaceAll() if you don't want to use regex

2022-01-12 20:15 UTC, merged